### ISSUE TITLE
Feature Request: allow configuration of domains

### ISSUE THREAD

**Issue by chris-koester** [paoloantinori/markdown_to_jira#3]
I would like to try the addon, but I am using a self hosted JIRA.
Therefore it would be great to have a way of whitelisting  other domains for this addon.

**Comment by Schweinepriester** [comment]
+1

**Comment by paoloantinori** [comment]
Added support to Chrome with this commit: https://github.com/paoloantinori/markdown_to_jira/commit/da708be094b183c8338b2efd7b11e251d7d0df34
